[package]
name = "gc"
version = "0.1.0"
authors = ["Daniel Liu <daniel.liu02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
